# Generated by Django 5.0.3 on 2025-01-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_reservation_client_reservation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='num_reservations',
        ),
    ]
